zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    global: /global/**
    gateway: /gateway/**

server:
  port: 8000
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript
    min-response-size: 2048

# Internationalization
spring.messages.basename: messages/messages

---
spring:
  config:
    activate:
      on-profile: docker
  zipkin:
    baseUrl: http://tracing:8201
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8102/eureka/
