spring:
  devtools:
    remote:
      secret: globalmysecret
---
spring:
  config:
    activate:
      on-profile: default
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}
---
spring:
  config:
    activate:
      on-profile: docker
  zipkin:
    baseUrl: http://tracing:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8080/eureka/
